// 批量生成单词数据 - 翻倍扩充每个年级的单词量
// 运行: node scripts/generate_words.js

const fs = require('fs');
const path = require('path');

// 新单词数据定义
const newWords = {
  grade1: {
    startId: 66,
    words: [
      { text: 'purple', phonetic: '/ˈpɜːpl/', meaning: '紫色', unit: '颜色' },
      { text: 'brown', phonetic: '/braʊn/', meaning: '棕色', unit: '颜色' },
      { text: 'gray', phonetic: '/ɡreɪ/', meaning: '灰色', unit: '颜色' },
      { text: 'gold', phonetic: '/ɡəʊld/', meaning: '金色', unit: '颜色' },
      { text: 'silver', phonetic: '/ˈsɪlvə/', meaning: '银色', unit: '颜色' },
      { text: 'spoon', phonetic: '/spuːn/', meaning: '勺子', unit: '餐具' },
      { text: 'fork', phonetic: '/fɔːk/', meaning: '叉子', unit: '餐具' },
      { text: 'knife', phonetic: '/naɪf/', meaning: '刀', unit: '餐具' },
      { text: 'plate', phonetic: '/pleɪt/', meaning: '盘子', unit: '餐具' },
      { text: 'cup', phonetic: '/kʌp/', meaning: '杯子', unit: '餐具' },
      { text: 'bowl', phonetic: '/bəʊl/', meaning: '碗', unit: '餐具' },
      { text: 'ant', phonetic: '/ænt/', meaning: '蚂蚁', unit: '动物' },
      { text: 'bee', phonetic: '/biː/', meaning: '蜜蜂', unit: '动物' },
      { text: 'fly', phonetic: '/flaɪ/', meaning: '苍蝇', unit: '动物' },
      { text: 'frog', phonetic: '/frɒɡ/', meaning: '青蛙', unit: '动物' },
      { text: 'snake', phonetic: '/sneɪk/', meaning: '蛇', unit: '动物' },
      { text: 'lion', phonetic: '/ˈlaɪən/', meaning: '狮子', unit: '动物' },
      { text: 'tiger', phonetic: '/ˈtaɪɡə/', meaning: '老虎', unit: '动物' },
      { text: 'monkey', phonetic: '/ˈmʌŋki/', meaning: '猴子', unit: '动物' },
      { text: 'panda', phonetic: '/ˈpændə/', meaning: '熊猫', unit: '动物' },
      { text: 'rabbit', phonetic: '/ˈræbɪt/', meaning: '兔子', unit: '动物' },
      { text: 'elephant', phonetic: '/ˈelɪfənt/', meaning: '大象', unit: '动物' },
      { text: 'giraffe', phonetic: '/dʒɪˈrɑːf/', meaning: '长颈鹿', unit: '动物' },
      { text: 'zebra', phonetic: '/ˈzebrə/', meaning: '斑马', unit: '动物' },
      { text: 'turtle', phonetic: '/ˈtɜːtl/', meaning: '乌龟', unit: '动物' },
      { text: 'hand', phonetic: '/hænd/', meaning: '手', unit: '身体' },
      { text: 'foot', phonetic: '/fʊt/', meaning: '脚', unit: '身体' },
      { text: 'arm', phonetic: '/ɑːm/', meaning: '手臂', unit: '身体' },
      { text: 'leg', phonetic: '/leɡ/', meaning: '腿', unit: '身体' },
      { text: 'head', phonetic: '/hed/', meaning: '头', unit: '身体' },
      { text: 'ear', phonetic: '/ɪə/', meaning: '耳朵', unit: '身体' },
      { text: 'nose', phonetic: '/nəʊz/', meaning: '鼻子', unit: '身体' },
      { text: 'mouth', phonetic: '/maʊθ/', meaning: '嘴巴', unit: '身体' },
      { text: 'tooth', phonetic: '/tuːθ/', meaning: '牙齿', unit: '身体' },
      { text: 'hair', phonetic: '/heə/', meaning: '头发', unit: '身体' },
      { text: 'sun', phonetic: '/sʌn/', meaning: '太阳', unit: '自然' },
      { text: 'moon', phonetic: '/muːn/', meaning: '月亮', unit: '自然' },
      { text: 'star', phonetic: '/stɑː/', meaning: '星星', unit: '自然' },
      { text: 'sky', phonetic: '/skaɪ/', meaning: '天空', unit: '自然' },
      { text: 'wind', phonetic: '/wɪnd/', meaning: '风', unit: '自然' },
      { text: 'snow', phonetic: '/snəʊ/', meaning: '雪', unit: '自然' },
      { text: 'ice', phonetic: '/aɪs/', meaning: '冰', unit: '自然' },
      { text: 'fire', phonetic: '/ˈfaɪə/', meaning: '火', unit: '自然' },
      { text: 'water', phonetic: '/ˈwɔːtə/', meaning: '水', unit: '自然' },
      { text: 'bread', phonetic: '/bred/', meaning: '面包', unit: '食物' },
      { text: 'rice', phonetic: '/raɪs/', meaning: '米饭', unit: '食物' },
      { text: 'meat', phonetic: '/miːt/', meaning: '肉', unit: '食物' },
      { text: 'egg', phonetic: '/eɡ/', meaning: '鸡蛋', unit: '食物' },
      { text: 'milk', phonetic: '/mɪlk/', meaning: '牛奶', unit: '食物' },
      { text: 'juice', phonetic: '/dʒuːs/', meaning: '果汁', unit: '食物' },
      { text: 'candy', phonetic: '/ˈkændi/', meaning: '糖果', unit: '食物' },
      { text: 'cake', phonetic: '/keɪk/', meaning: '蛋糕', unit: '食物' },
      { text: 'cookie', phonetic: '/ˈkʊki/', meaning: '饼干', unit: '食物' },
      { text: 'soup', phonetic: '/suːp/', meaning: '汤', unit: '食物' },
      { text: 'salad', phonetic: '/ˈsæləd/', meaning: '沙拉', unit: '食物' },
      { text: 'tree', phonetic: '/triː/', meaning: '树', unit: '自然' },
      { text: 'flower', phonetic: '/ˈflaʊə/', meaning: '花', unit: '自然' },
      { text: 'grass', phonetic: '/ɡrɑːs/', meaning: '草', unit: '自然' },
      { text: 'leaf', phonetic: '/liːf/', meaning: '叶子', unit: '自然' },
      { text: 'ring', phonetic: '/rɪŋ/', meaning: '戒指', unit: '物品' },
      { text: 'bell', phonetic: '/bel/', meaning: '铃铛', unit: '物品' },
      { text: 'map', phonetic: '/mæp/', meaning: '地图', unit: '物品' },
      { text: 'key', phonetic: '/kiː/', meaning: '钥匙', unit: '物品' },
      { text: 'gift', phonetic: '/ɡɪft/', meaning: '礼物', unit: '物品' },
      { text: 'flag', phonetic: '/flæɡ/', meaning: '旗子', unit: '物品' },
    ]
  },
  grade2: {
    startId: 66,
    words: [
      { text: 'mountain', phonetic: '/ˈmaʊntɪn/', meaning: '山', unit: '自然' },
      { text: 'river', phonetic: '/ˈrɪvə/', meaning: '河流', unit: '自然' },
      { text: 'lake', phonetic: '/leɪk/', meaning: '湖', unit: '自然' },
      { text: 'forest', phonetic: '/ˈfɒrɪst/', meaning: '森林', unit: '自然' },
      { text: 'park', phonetic: '/pɑːk/', meaning: '公园', unit: '地点' },
      { text: 'bridge', phonetic: '/brɪdʒ/', meaning: '桥', unit: '地点' },
      { text: 'road', phonetic: '/rəʊd/', meaning: '道路', unit: '地点' },
      { text: 'street', phonetic: '/striːt/', meaning: '街道', unit: '地点' },
      { text: 'shop', phonetic: '/ʃɒp/', meaning: '商店', unit: '地点' },
      { text: 'store', phonetic: '/stɔː/', meaning: '店铺', unit: '地点' },
      { text: 'bank', phonetic: '/bæŋk/', meaning: '银行', unit: '地点' },
      { text: 'hospital', phonetic: '/ˈhɒspɪtl/', meaning: '医院', unit: '地点' },
      { text: 'library', phonetic: '/ˈlaɪbrəri/', meaning: '图书馆', unit: '地点' },
      { text: 'cinema', phonetic: '/ˈsɪnəmə/', meaning: '电影院', unit: '地点' },
      { text: 'station', phonetic: '/ˈsteɪʃn/', meaning: '车站', unit: '地点' },
      { text: 'airport', phonetic: '/ˈeəpɔːt/', meaning: '机场', unit: '地点' },
      { text: 'boat', phonetic: '/bəʊt/', meaning: '小船', unit: '交通' },
      { text: 'ship', phonetic: '/ʃɪp/', meaning: '大船', unit: '交通' },
      { text: 'train', phonetic: '/treɪn/', meaning: '火车', unit: '交通' },
      { text: 'bus', phonetic: '/bʌs/', meaning: '公共汽车', unit: '交通' },
      { text: 'taxi', phonetic: '/ˈtæksi/', meaning: '出租车', unit: '交通' },
      { text: 'bike', phonetic: '/baɪk/', meaning: '自行车', unit: '交通' },
      { text: 'guitar', phonetic: '/ɡɪˈtɑː/', meaning: '吉他', unit: '音乐' },
      { text: 'piano', phonetic: '/piˈænəʊ/', meaning: '钢琴', unit: '音乐' },
      { text: 'drum', phonetic: '/drʌm/', meaning: '鼓', unit: '音乐' },
      { text: 'violin', phonetic: '/ˌvaɪəˈlɪn/', meaning: '小提琴', unit: '音乐' },
      { text: 'flute', phonetic: '/fluːt/', meaning: '笛子', unit: '音乐' },
      { text: 'chess', phonetic: '/tʃes/', meaning: '国际象棋', unit: '游戏' },
      { text: 'ball', phonetic: '/bɔːl/', meaning: '球', unit: '游戏' },
      { text: 'kite', phonetic: '/kaɪt/', meaning: '风筝', unit: '游戏' },
      { text: 'doll', phonetic: '/dɒl/', meaning: '洋娃娃', unit: '游戏' },
      { text: 'robot', phonetic: '/ˈrəʊbɒt/', meaning: '机器人', unit: '游戏' },
      { text: 'puzzle', phonetic: '/ˈpʌzl/', meaning: '拼图', unit: '游戏' },
      { text: 'camera', phonetic: '/ˈkæmərə/', meaning: '相机', unit: '物品' },
      { text: 'phone', phonetic: '/fəʊn/', meaning: '电话', unit: '物品' },
      { text: 'clock', phonetic: '/klɒk/', meaning: '时钟', unit: '物品' },
      { text: 'watch', phonetic: '/wɒtʃ/', meaning: '手表', unit: '物品' },
      { text: 'radio', phonetic: '/ˈreɪdiəʊ/', meaning: '收音机', unit: '物品' },
      { text: 'computer', phonetic: '/kəmˈpjuːtə/', meaning: '电脑', unit: '物品' },
      { text: 'keyboard', phonetic: '/ˈkiːbɔːd/', meaning: '键盘', unit: '物品' },
      { text: 'screen', phonetic: '/skriːn/', meaning: '屏幕', unit: '物品' },
      { text: 'mouse', phonetic: '/maʊs/', meaning: '鼠标', unit: '物品' },
      { text: 'crayon', phonetic: '/ˈkreɪən/', meaning: '蜡笔', unit: '文具' },
      { text: 'marker', phonetic: '/ˈmɑːkə/', meaning: '马克笔', unit: '文具' },
      { text: 'eraser', phonetic: '/ɪˈreɪzə/', meaning: '橡皮', unit: '文具' },
      { text: 'glue', phonetic: '/ɡluː/', meaning: '胶水', unit: '文具' },
      { text: 'tape', phonetic: '/teɪp/', meaning: '胶带', unit: '文具' },
      { text: 'ruler', phonetic: '/ˈruːlə/', meaning: '尺子', unit: '文具' },
      { text: 'scissors', phonetic: '/ˈsɪzəz/', meaning: '剪刀', unit: '文具' },
      { text: 'pencil', phonetic: '/ˈpensl/', meaning: '铅笔', unit: '文具' },
      { text: 'garden', phonetic: '/ˈɡɑːdn/', meaning: '花园', unit: '地点' },
      { text: 'swing', phonetic: '/swɪŋ/', meaning: '秋千', unit: '游戏' },
      { text: 'slide', phonetic: '/slaɪd/', meaning: '滑梯', unit: '游戏' },
      { text: 'sandbox', phonetic: '/ˈsændbɒks/', meaning: '沙坑', unit: '游戏' },
      { text: 'tablet', phonetic: '/ˈtæblɪt/', meaning: '平板电脑', unit: '物品' },
      { text: 'printer', phonetic: '/ˈprɪntə/', meaning: '打印机', unit: '物品' },
      { text: 'block', phonetic: '/blɒk/', meaning: '积木', unit: '游戏' },
      { text: 'card', phonetic: '/kɑːd/', meaning: '卡片', unit: '游戏' },
      { text: 'scooter', phonetic: '/ˈskuːtə/', meaning: '滑板车', unit: '交通' },
    ]
  },
  grade3: {
    startId: 66,
    words: [
      { text: 'weather', phonetic: '/ˈweðə/', meaning: '天气', unit: '天气' },
      { text: 'season', phonetic: '/ˈsiːzn/', meaning: '季节', unit: '季节' },
      { text: 'temperature', phonetic: '/ˈtemprətʃə/', meaning: '温度', unit: '天气' },
      { text: 'degree', phonetic: '/dɪˈɡriː/', meaning: '度；度数', unit: '天气' },
      { text: 'foggy', phonetic: '/ˈfɒɡi/', meaning: '有雾的', unit: '天气' },
      { text: 'stormy', phonetic: '/ˈstɔːmi/', meaning: '暴风雨的', unit: '天气' },
      { text: 'rainbow', phonetic: '/ˈreɪnbəʊ/', meaning: '彩虹', unit: '自然' },
      { text: 'thunder', phonetic: '/ˈθʌndə/', meaning: '雷声', unit: '自然' },
      { text: 'lightning', phonetic: '/ˈlaɪtnɪŋ/', meaning: '闪电', unit: '自然' },
      { text: 'umbrella', phonetic: '/ʌmˈbrelə/', meaning: '雨伞', unit: '物品' },
      { text: 'raincoat', phonetic: '/ˈreɪnkəʊt/', meaning: '雨衣', unit: '衣物' },
      { text: 'boot', phonetic: '/buːt/', meaning: '靴子', unit: '衣物' },
      { text: 'glove', phonetic: '/ɡlʌv/', meaning: '手套', unit: '衣物' },
      { text: 'scarf', phonetic: '/skɑːf/', meaning: '围巾', unit: '衣物' },
      { text: 'sweater', phonetic: '/ˈswetə/', meaning: '毛衣', unit: '衣物' },
      { text: 'jacket', phonetic: '/ˈdʒækɪt/', meaning: '夹克', unit: '衣物' },
      { text: 'coat', phonetic: '/kəʊt/', meaning: '外套', unit: '衣物' },
      { text: 'dress', phonetic: '/dres/', meaning: '连衣裙', unit: '衣物' },
      { text: 'skirt', phonetic: '/skɜːt/', meaning: '裙子', unit: '衣物' },
      { text: 'shirt', phonetic: '/ʃɜːt/', meaning: '衬衫', unit: '衣物' },
      { text: 'pants', phonetic: '/pænts/', meaning: '裤子', unit: '衣物' },
      { text: 'shorts', phonetic: '/ʃɔːts/', meaning: '短裤', unit: '衣物' },
      { text: 'socks', phonetic: '/sɒks/', meaning: '袜子', unit: '衣物' },
      { text: 'shoes', phonetic: '/ʃuːz/', meaning: '鞋子', unit: '衣物' },
      { text: 'hat', phonetic: '/hæt/', meaning: '帽子', unit: '衣物' },
      { text: 'belt', phonetic: '/belt/', meaning: '皮带', unit: '衣物' },
      { text: 'pocket', phonetic: '/ˈpɒkɪt/', meaning: '口袋', unit: '衣物' },
      { text: 'button', phonetic: '/ˈbʌtn/', meaning: '纽扣', unit: '衣物' },
      { text: 'mirror', phonetic: '/ˈmɪrə/', meaning: '镜子', unit: '物品' },
      { text: 'towel', phonetic: '/ˈtaʊəl/', meaning: '毛巾', unit: '物品' },
      { text: 'soap', phonetic: '/səʊp/', meaning: '肥皂', unit: '物品' },
      { text: 'toothbrush', phonetic: '/ˈtuːθbrʌʃ/', meaning: '牙刷', unit: '物品' },
      { text: 'toothpaste', phonetic: '/ˈtuːθpeɪst/', meaning: '牙膏', unit: '物品' },
      { text: 'comb', phonetic: '/kəʊm/', meaning: '梳子', unit: '物品' },
      { text: 'brush', phonetic: '/brʌʃ/', meaning: '刷子', unit: '物品' },
      { text: 'shower', phonetic: '/ˈʃaʊə/', meaning: '淋浴', unit: '物品' },
      { text: 'bath', phonetic: '/bɑːθ/', meaning: '浴缸', unit: '物品' },
      { text: 'sink', phonetic: '/sɪŋk/', meaning: '水槽', unit: '物品' },
      { text: 'toilet', phonetic: '/ˈtɔɪlɪt/', meaning: '厕所', unit: '房间' },
      { text: 'bedroom', phonetic: '/ˈbedruːm/', meaning: '卧室', unit: '房间' },
      { text: 'kitchen', phonetic: '/ˈkɪtʃɪn/', meaning: '厨房', unit: '房间' },
      { text: 'bathroom', phonetic: '/ˈbɑːθruːm/', meaning: '浴室', unit: '房间' },
      { text: 'balcony', phonetic: '/ˈbælkəni/', meaning: '阳台', unit: '房间' },
      { text: 'ceiling', phonetic: '/ˈsiːlɪŋ/', meaning: '天花板', unit: '房间' },
      { text: 'floor', phonetic: '/flɔː/', meaning: '地板', unit: '房间' },
      { text: 'wall', phonetic: '/wɔːl/', meaning: '墙', unit: '房间' },
      { text: 'door', phonetic: '/dɔː/', meaning: '门', unit: '房间' },
      { text: 'window', phonetic: '/ˈwɪndəʊ/', meaning: '窗户', unit: '房间' },
      { text: 'curtain', phonetic: '/ˈkɜːtn/', meaning: '窗帘', unit: '房间' },
      { text: 'carpet', phonetic: '/ˈkɑːpɪt/', meaning: '地毯', unit: '房间' },
      { text: 'lamp', phonetic: '/læmp/', meaning: '台灯', unit: '物品' },
      { text: 'zipper', phonetic: '/ˈzɪpə/', meaning: '拉链', unit: '衣物' },
      { text: 'living room', phonetic: '/ˈlɪvɪŋ ruːm/', meaning: '客厅', unit: '房间' },
    ]
  },
  grade4: {
    startId: 71,
    words: [
      { text: 'uncle', phonetic: '/ˈʌŋkl/', meaning: '叔叔；伯伯', unit: '家庭' },
      { text: 'aunt', phonetic: '/ɑːnt/', meaning: '阿姨；姑姑', unit: '家庭' },
      { text: 'cousin', phonetic: '/ˈkʌzn/', meaning: '表兄弟；表姐妹', unit: '家庭' },
      { text: 'nephew', phonetic: '/ˈnefjuː/', meaning: '侄子；外甥', unit: '家庭' },
      { text: 'niece', phonetic: '/niːs/', meaning: '侄女；外甥女', unit: '家庭' },
      { text: 'husband', phonetic: '/ˈhʌzbənd/', meaning: '丈夫', unit: '家庭' },
      { text: 'wife', phonetic: '/waɪf/', meaning: '妻子', unit: '家庭' },
      { text: 'parent', phonetic: '/ˈpeərənt/', meaning: '父母', unit: '家庭' },
      { text: 'teenager', phonetic: '/ˈtiːneɪdʒə/', meaning: '青少年', unit: '人物' },
      { text: 'neighbor', phonetic: '/ˈneɪbə/', meaning: '邻居', unit: '人物' },
      { text: 'stranger', phonetic: '/ˈstreɪndʒə/', meaning: '陌生人', unit: '人物' },
      { text: 'teammate', phonetic: '/ˈtiːmmeɪt/', meaning: '队友', unit: '人物' },
      { text: 'classmate', phonetic: '/ˈklɑːsmeɪt/', meaning: '同学', unit: '人物' },
      { text: 'roommate', phonetic: '/ˈruːmmeɪt/', meaning: '室友', unit: '人物' },
      { text: 'partner', phonetic: '/ˈpɑːtnə/', meaning: '搭档', unit: '人物' },
      { text: 'boss', phonetic: '/bɒs/', meaning: '老板', unit: '职业' },
      { text: 'worker', phonetic: '/ˈwɜːkə/', meaning: '工人', unit: '职业' },
      { text: 'farmer', phonetic: '/ˈfɑːmə/', meaning: '农民', unit: '职业' },
      { text: 'driver', phonetic: '/ˈdraɪvə/', meaning: '司机', unit: '职业' },
      { text: 'painter', phonetic: '/ˈpeɪntə/', meaning: '画家', unit: '职业' },
      { text: 'singer', phonetic: '/ˈsɪŋə/', meaning: '歌手', unit: '职业' },
      { text: 'dancer', phonetic: '/ˈdɑːnsə/', meaning: '舞者', unit: '职业' },
      { text: 'writer', phonetic: '/ˈraɪtə/', meaning: '作家', unit: '职业' },
      { text: 'actor', phonetic: '/ˈæktə/', meaning: '演员', unit: '职业' },
      { text: 'doctor', phonetic: '/ˈdɒktə/', meaning: '医生', unit: '职业' },
      { text: 'nurse', phonetic: '/nɜːs/', meaning: '护士', unit: '职业' },
      { text: 'police', phonetic: '/pəˈliːs/', meaning: '警察', unit: '职业' },
      { text: 'firefighter', phonetic: '/ˈfaɪəfaɪtə/', meaning: '消防员', unit: '职业' },
      { text: 'soldier', phonetic: '/ˈsəʊldʒə/', meaning: '士兵', unit: '职业' },
      { text: 'pilot', phonetic: '/ˈpaɪlət/', meaning: '飞行员', unit: '职业' },
      { text: 'chef', phonetic: '/ʃef/', meaning: '厨师', unit: '职业' },
      { text: 'waiter', phonetic: '/ˈweɪtə/', meaning: '服务员', unit: '职业' },
      { text: 'engineer', phonetic: '/ˌendʒɪˈnɪə/', meaning: '工程师', unit: '职业' },
      { text: 'scientist', phonetic: '/ˈsaɪəntɪst/', meaning: '科学家', unit: '职业' },
      { text: 'artist', phonetic: '/ˈɑːtɪst/', meaning: '艺术家', unit: '职业' },
      { text: 'musician', phonetic: '/mjuˈzɪʃn/', meaning: '音乐家', unit: '职业' },
      { text: 'athlete', phonetic: '/ˈæθliːt/', meaning: '运动员', unit: '职业' },
      { text: 'runner', phonetic: '/ˈrʌnə/', meaning: '跑步者', unit: '职业' },
      { text: 'swimmer', phonetic: '/ˈswɪmə/', meaning: '游泳者', unit: '职业' },
      { text: 'player', phonetic: '/ˈpleɪə/', meaning: '选手', unit: '职业' },
      { text: 'coach', phonetic: '/kəʊtʃ/', meaning: '教练', unit: '职业' },
      { text: 'captain', phonetic: '/ˈkæptɪn/', meaning: '队长', unit: '人物' },
      { text: 'leader', phonetic: '/ˈliːdə/', meaning: '领导', unit: '人物' },
      { text: 'member', phonetic: '/ˈmembə/', meaning: '成员', unit: '人物' },
      { text: 'group', phonetic: '/ɡruːp/', meaning: '小组', unit: '人物' },
      { text: 'family', phonetic: '/ˈfæməli/', meaning: '家庭', unit: '家庭' },
    ]
  },
  grade5: {
    startId: 71,
    words: [
      { text: 'prepare', phonetic: '/prɪˈpeə/', meaning: '准备', unit: '动词' },
      { text: 'explain', phonetic: '/ɪkˈspleɪn/', meaning: '解释', unit: '动词' },
      { text: 'describe', phonetic: '/dɪˈskraɪb/', meaning: '描述', unit: '动词' },
      { text: 'compare', phonetic: '/kəmˈpeə/', meaning: '比较', unit: '动词' },
      { text: 'analyze', phonetic: '/ˈænəlaɪz/', meaning: '分析', unit: '动词' },
      { text: 'evaluate', phonetic: '/ɪˈvæljueɪt/', meaning: '评估', unit: '动词' },
      { text: 'organize', phonetic: '/ˈɔːɡənaɪz/', meaning: '组织', unit: '动词' },
      { text: 'arrange', phonetic: '/əˈreɪndʒ/', meaning: '安排', unit: '动词' },
      { text: 'collect', phonetic: '/kəˈlekt/', meaning: '收集', unit: '动词' },
      { text: 'connect', phonetic: '/kəˈnekt/', meaning: '连接', unit: '动词' },
      { text: 'create', phonetic: '/kriˈeɪt/', meaning: '创造', unit: '动词' },
      { text: 'design', phonetic: '/dɪˈzaɪn/', meaning: '设计', unit: '动词' },
      { text: 'develop', phonetic: '/dɪˈveləp/', meaning: '发展；开发', unit: '动词' },
      { text: 'discover', phonetic: '/dɪˈskʌvə/', meaning: '发现', unit: '动词' },
      { text: 'explore', phonetic: '/ɪkˈsplɔː/', meaning: '探索', unit: '动词' },
      { text: 'imagine', phonetic: '/ɪˈmædʒɪn/', meaning: '想象', unit: '动词' },
      { text: 'invent', phonetic: '/ɪnˈvent/', meaning: '发明', unit: '动词' },
      { text: 'measure', phonetic: '/ˈmeʒə/', meaning: '测量', unit: '动词' },
      { text: 'observe', phonetic: '/əbˈzɜːv/', meaning: '观察', unit: '动词' },
      { text: 'predict', phonetic: '/prɪˈdɪkt/', meaning: '预测', unit: '动词' },
      { text: 'record', phonetic: '/rɪˈkɔːd/', meaning: '记录', unit: '动词' },
      { text: 'report', phonetic: '/rɪˈpɔːt/', meaning: '报告', unit: '动词' },
      { text: 'research', phonetic: '/rɪˈsɜːtʃ/', meaning: '研究', unit: '动词' },
      { text: 'solve', phonetic: '/sɒlv/', meaning: '解决', unit: '动词' },
      { text: 'calculate', phonetic: '/ˈkælkjuleɪt/', meaning: '计算', unit: '动词' },
      { text: 'estimate', phonetic: '/ˈestɪmeɪt/', meaning: '估计', unit: '动词' },
      { text: 'data', phonetic: '/ˈdeɪtə/', meaning: '数据', unit: '名词' },
      { text: 'result', phonetic: '/rɪˈzʌlt/', meaning: '结果', unit: '名词' },
      { text: 'method', phonetic: '/ˈmeθəd/', meaning: '方法', unit: '名词' },
      { text: 'process', phonetic: '/ˈprəʊses/', meaning: '过程', unit: '名词' },
      { text: 'experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: '实验', unit: '名词' },
      { text: 'theory', phonetic: '/ˈθɪəri/', meaning: '理论', unit: '名词' },
      { text: 'prove', phonetic: '/pruːv/', meaning: '证明', unit: '动词' },
      { text: 'improve', phonetic: '/ɪmˈpruːv/', meaning: '提高；改善', unit: '动词' },
      { text: 'increase', phonetic: '/ɪnˈkriːs/', meaning: '增加', unit: '动词' },
      { text: 'decrease', phonetic: '/dɪˈkriːs/', meaning: '减少', unit: '动词' },
      { text: 'continue', phonetic: '/kənˈtɪnjuː/', meaning: '继续', unit: '动词' },
      { text: 'complete', phonetic: '/kəmˈpliːt/', meaning: '完成', unit: '动词' },
      { text: 'achieve', phonetic: '/əˈtʃiːv/', meaning: '达到；实现', unit: '动词' },
      { text: 'succeed', phonetic: '/səkˈsiːd/', meaning: '成功', unit: '动词' },
      { text: 'attempt', phonetic: '/əˈtempt/', meaning: '尝试', unit: '动词' },
      { text: 'effort', phonetic: '/ˈefət/', meaning: '努力', unit: '名词' },
      { text: 'review', phonetic: '/rɪˈvjuː/', meaning: '复习', unit: '动词' },
      { text: 'revise', phonetic: '/rɪˈvaɪz/', meaning: '修订', unit: '动词' },
      { text: 'correct', phonetic: '/kəˈrekt/', meaning: '正确的；纠正', unit: '形容词' },
      { text: 'error', phonetic: '/ˈerə/', meaning: '错误', unit: '名词' },
      { text: 'solution', phonetic: '/səˈluːʃn/', meaning: '解决方案', unit: '名词' },
    ]
  },
  grade6: {
    startId: 71,
    words: [
      { text: 'environment', phonetic: '/ɪnˈvaɪrənmənt/', meaning: '环境', unit: '自然' },
      { text: 'pollution', phonetic: '/pəˈluːʃn/', meaning: '污染', unit: '自然' },
      { text: 'recycle', phonetic: '/ˌriːˈsaɪkl/', meaning: '回收', unit: '动词' },
      { text: 'energy', phonetic: '/ˈenədʒi/', meaning: '能源', unit: '自然' },
      { text: 'fuel', phonetic: '/fjuːəl/', meaning: '燃料', unit: '自然' },
      { text: 'electricity', phonetic: '/ɪˌlekˈtrɪsəti/', meaning: '电', unit: '自然' },
      { text: 'gas', phonetic: '/ɡæs/', meaning: '天然气；煤气', unit: '自然' },
      { text: 'oil', phonetic: '/ɔɪl/', meaning: '石油', unit: '自然' },
      { text: 'coal', phonetic: '/kəʊl/', meaning: '煤', unit: '自然' },
      { text: 'solar', phonetic: '/ˈsəʊlə/', meaning: '太阳的', unit: '形容词' },
      { text: 'power', phonetic: '/ˈpaʊə/', meaning: '电力；力量', unit: '自然' },
      { text: 'resource', phonetic: '/rɪˈzɔːs/', meaning: '资源', unit: '名词' },
      { text: 'material', phonetic: '/məˈtɪəriəl/', meaning: '材料', unit: '名词' },
      { text: 'plastic', phonetic: '/ˈplæstɪk/', meaning: '塑料', unit: '材料' },
      { text: 'metal', phonetic: '/ˈmetl/', meaning: '金属', unit: '材料' },
      { text: 'glass', phonetic: '/ɡlɑːs/', meaning: '玻璃', unit: '材料' },
      { text: 'wood', phonetic: '/wʊd/', meaning: '木头', unit: '材料' },
      { text: 'cloth', phonetic: '/klɒθ/', meaning: '布料', unit: '材料' },
      { text: 'leather', phonetic: '/ˈleðə/', meaning: '皮革', unit: '材料' },
      { text: 'rubber', phonetic: '/ˈrʌbə/', meaning: '橡胶', unit: '材料' },
      { text: 'chemical', phonetic: '/ˈkemɪkl/', meaning: '化学物质', unit: '名词' },
      { text: 'natural', phonetic: '/ˈnætʃrəl/', meaning: '自然的', unit: '形容词' },
      { text: 'artificial', phonetic: '/ˌɑːtɪˈfɪʃl/', meaning: '人造的', unit: '形容词' },
      { text: 'organic', phonetic: '/ɔːˈɡænɪk/', meaning: '有机的', unit: '形容词' },
      { text: 'reuse', phonetic: '/ˌriːˈjuːz/', meaning: '重复使用', unit: '动词' },
      { text: 'reduce', phonetic: '/rɪˈdjuːs/', meaning: '减少', unit: '动词' },
      { text: 'protect', phonetic: '/prəˈtekt/', meaning: '保护', unit: '动词' },
      { text: 'trash', phonetic: '/træʃ/', meaning: '垃圾', unit: '名词' },
      { text: 'landfill', phonetic: '/ˈlændfɪl/', meaning: '垃圾填埋场', unit: '名词' },
      { text: 'ocean', phonetic: '/ˈəʊʃn/', meaning: '海洋', unit: '自然' },
      { text: 'sea', phonetic: '/siː/', meaning: '大海', unit: '自然' },
      { text: 'coast', phonetic: '/kəʊst/', meaning: '海岸', unit: '自然' },
      { text: 'desert', phonetic: '/ˈdezət/', meaning: '沙漠', unit: '自然' },
      { text: 'jungle', phonetic: '/ˈdʒʌŋɡl/', meaning: '丛林', unit: '自然' },
      { text: 'valley', phonetic: '/ˈvæli/', meaning: '山谷', unit: '自然' },
      { text: 'hill', phonetic: '/hɪl/', meaning: '小山', unit: '自然' },
      { text: 'plain', phonetic: '/pleɪn/', meaning: '平原', unit: '自然' },
      { text: 'field', phonetic: '/fiːld/', meaning: '田地', unit: '自然' },
      { text: 'farm', phonetic: '/fɑːm/', meaning: '农场', unit: '自然' },
      { text: 'crop', phonetic: '/krɒp/', meaning: '庄稼', unit: '自然' },
      { text: 'harvest', phonetic: '/ˈhɑːvɪst/', meaning: '收获', unit: '名词' },
      { text: 'plant', phonetic: '/plɑːnt/', meaning: '植物；种植', unit: '动词' },
      { text: 'seed', phonetic: '/siːd/', meaning: '种子', unit: '自然' },
      { text: 'soil', phonetic: '/sɔɪl/', meaning: '土壤', unit: '自然' },
      { text: 'fertilizer', phonetic: '/ˈfɜːtəlaɪzə/', meaning: '肥料', unit: '名词' },
      { text: 'pesticide', phonetic: '/ˈpestɪsaɪd/', meaning: '杀虫剂', unit: '名词' },
      { text: 'insect', phonetic: '/ˈɪnsekt/', meaning: '昆虫', unit: '动物' },
      { text: 'pest', phonetic: '/pest/', meaning: '害虫', unit: '动物' },
    ]
  }
};

function generateExample(text, meaning) {
  const examples = {
    purple: ['The grape is purple.', '葡萄是紫色的。'],
    brown: ['The bear is brown.', '熊是棕色的。'],
    gray: ['The cloud is gray.', '云是灰色的。'],
    gold: ['The star is gold.', '星星是金色的。'],
    silver: ['The moon is silver.', '月亮是银色的。'],
    spoon: ['I eat soup with a spoon.', '我用勺子喝汤。'],
    fork: ['Use a fork to eat.', '用叉子吃饭。'],
    knife: ['Cut with a knife.', '用刀切东西。'],
    plate: ['The cake is on the plate.', '蛋糕在盘子上。'],
    cup: ['I drink milk from a cup.', '我用杯子喝牛奶。'],
    bowl: ['Rice is in the bowl.', '米饭在碗里。'],
    ant: ['The ant is very small.', '蚂蚁很小。'],
    bee: ['The bee makes honey.', '蜜蜂会酿蜜。'],
    fly: ['A fly is on the table.', '一只苍蝇在桌子上。'],
    frog: ['The frog jumps high.', '青蛙跳得很高。'],
    snake: ['The snake is long.', '蛇很长。'],
    lion: ['The lion is the king.', '狮子是百兽之王。'],
    tiger: ['The tiger is strong.', '老虎很强壮。'],
    monkey: ['The monkey is funny.', '猴子很有趣。'],
    panda: ['I love the panda.', '我爱熊猫。'],
    rabbit: ['The rabbit is white.', '兔子是白色的。'],
    elephant: ['The elephant is big.', '大象很大。'],
    giraffe: ['The giraffe has a long neck.', '长颈鹿有长脖子。'],
    zebra: ['The zebra has stripes.', '斑马有条纹。'],
    turtle: ['The turtle walks slowly.', '乌龟走得很慢。'],
    hand: ['Wash your hands.', '洗洗你的手。'],
    foot: ['My foot hurts.', '我脚疼。'],
    arm: ['He broke his arm.', '他手臂骨折了。'],
    leg: ['She has long legs.', '她腿很长。'],
    head: ['I have a headache.', '我头痛。'],
    ear: ['Listen with your ears.', '用耳朵听。'],
    nose: ['She has a small nose.', '她鼻子很小。'],
    mouth: ['Open your mouth.', '张开你的嘴。'],
    tooth: ['The tooth is white.', '牙齿是白的。'],
    hair: ['She has long hair.', '她头发很长。'],
    sun: ['The sun is bright.', '太阳很亮。'],
    moon: ['The moon is full.', '月亮圆了。'],
    star: ['I see a star in the sky.', '我看到天上的星星。'],
    sky: ['The sky is blue.', '天空是蓝色的。'],
    wind: ['The wind is strong.', '风很大。'],
    snow: ['Children play in the snow.', '孩子们在雪里玩。'],
    ice: ['The ice is cold.', '冰很冷。'],
    fire: ['Fire is hot.', '火很热。'],
    water: ['Drink more water.', '多喝点水。'],
    bread: ['I like bread for breakfast.', '我早饭喜欢吃面包。'],
    rice: ['We eat rice every day.', '我们每天吃米饭。'],
    meat: ['I like chicken meat.', '我喜欢吃鸡肉。'],
    egg: ['The egg is fresh.', '鸡蛋很新鲜。'],
    milk: ['I drink milk every morning.', '我每天早上喝牛奶。'],
    juice: ['Orange juice is yummy.', '橙汁很好喝。'],
    candy: ['I love candy.', '我喜欢糖果。'],
    cake: ['The cake is sweet.', '蛋糕很甜。'],
    cookie: ['Have a cookie.', '吃块饼干吧。'],
    soup: ['The soup is hot.', '汤很烫。'],
    salad: ['I like fruit salad.', '我喜欢水果沙拉。'],
    tree: ['The tree is tall.', '树很高。'],
    flower: ['The flower is beautiful.', '花很美。'],
    grass: ['The grass is green.', '草是绿色的。'],
    leaf: ['The leaf is yellow.', '叶子是黄色的。'],
    ring: ['She wears a ring.', '她戴着戒指。'],
    bell: ['The bell rings.', '铃声响了。'],
    map: ['Look at the map.', '看看地图。'],
    key: ['I lost my key.', '我丢了钥匙。'],
    gift: ['Thank you for the gift.', '谢谢你的礼物。'],
    flag: ['The flag waves.', '旗子在飘扬。'],
  };

  if (examples[text]) return examples[text];
  // Default example
  const u = text.charAt(0).toUpperCase() + text.slice(1);
  return [`I see a ${text}.`, `我看到一个${meaning}。`];
}

function generateMemoryTip(text, meaning) {
  return [
    { type: 'association', content: `${text} → ${meaning}的英文` }
  ];
}

function generateNewWords(gradeId, startId, words) {
  return words.map((w, i) => {
    const id = `${gradeId}-w${startId + i}`;
    const [example, exampleMeaning] = generateExample(w.text, w.meaning);
    const text = w.text;
    const upperText = text.charAt(0).toUpperCase() + text.slice(1);
    return {
      id,
      text,
      phonetic: w.phonetic,
      meaning: w.meaning,
      example: example || `${upperText} is a common word.`,
      exampleMeaning: exampleMeaning || `${w.meaning}是一个常用词。`,
      unit: w.unit,
      memoryTips: generateMemoryTip(text, w.meaning),
    };
  });
}

const gradeMap = {
  grade1: { file: 'grade1.ts', gradeId: 'g1' },
  grade2: { file: 'grade2.ts', gradeId: 'g2' },
  grade3: { file: 'grade3.ts', gradeId: 'g3' },
  grade4: { file: 'grade4.ts', gradeId: 'g4' },
  grade5: { file: 'grade5.ts', gradeId: 'g5' },
  grade6: { file: 'grade6.ts', gradeId: 'g6' },
};

for (const [key, config] of Object.entries(gradeMap)) {
  const data = newWords[key];
  if (!data) continue;

  const filePath = path.join(__dirname, '..', 'src', 'data', 'words', config.file);
  let content = fs.readFileSync(filePath, 'utf8');

  const words = generateNewWords(config.gradeId, data.startId, data.words);
  const wordsStr = words.map(w => {
    const safeExample = w.example.replace(/['']/g, "'");
    const safeExampleMeaning = w.exampleMeaning.replace(/['']/g, "'");
    const safeMeaning = w.meaning.replace(/['']/g, "'");
    return `  {
    id: '${w.id}',
    text: '${w.text}',
    phonetic: '${w.phonetic}',
    meaning: '${safeMeaning}',
    example: '${safeExample}',
    exampleMeaning: '${safeExampleMeaning}',
    unit: '${w.unit}',
    memoryTips: [
      { type: 'association', content: '${w.text} \\u2192 ${safeMeaning}' }
    ]
  }`;
  }).join(',\n');

  // Insert before closing ];
  content = content.replace(/\n\];$/, `,\n${wordsStr}\n];`);

  fs.writeFileSync(filePath, content, 'utf8');
  console.log(`✅ ${config.file}: added ${words.length} words (total with ~${newWords[key].startId + words.length} entries)`);
}
